### ISSUE TITLE
Return promises to make use of async/await

### ISSUE THREAD

**Issue by email2vimalraj** [splunk/splunk-sdk-javascript#81]
Currently there are too many callbacks (ex: search with polling), it is kind of confusing users on handling. Can we just return promises and users can use the modern async/await to get the information required?

I'm being stumbled upon where I've to stream the preview results whenever it is available. This would be a great addition and will improve DX.

**Comment by shakeelmohamed** [comment]
Hi @email2vimalraj thanks for your issue. This is going to be a significant refactor throughout the SDK which I'm not sure we're planning on taking on at this time. If we put investment into this SDK, we'll bring in modern JS features such as async/await.

**Comment by email2vimalraj** [comment]
Hi @shakeelmohamed , thanks for quickly looking at the issue. Can we at least keep this issue open and track?

So that we can know if someone voting for the issue and can prioritize.

Please let me know what you think.

**Comment by PixnBits** [comment]
The [search example](https://github.com/splunk/splunk-sdk-javascript/blob/1.9.0/examples/node/search.js) shows the last commit to be from 2012, coming up on 8 years ago. The JavaScript standard has changed quite a bit since then; using `splunkjs.Async` in an example is a red flag of the lack of maintenance of this package which is a common qualification when choosing dependencies. I'm hoping "If we put investment into this SDK" becomes "When".

**Comment by shakeelmohamed** [comment]
@PixnBits we appreciate your concern and are well aware of the shortcomings of this SDK. As very small team of SDK maintainers we have to constantly reprioritize what we're working on in order to  maximize customer value. Sometimes we're going to fall short. We more than welcome any pull requests if you or anyone else is interested in helping to improve our developer tooling for the Splunk developer community. We are absolutely doing the best we can and we thank you for your patience.

I've re-opened the issue for tracking purposes as @email2vimalraj suggested.

**Comment by jose-pr** [comment]
> @PixnBits we appreciate your concern and are well aware of the shortcomings of this SDK. As very small team of SDK maintainers we have to constantly reprioritize what we're working on in order to maximize customer value. Sometimes we're going to fall short. We more than welcome any pull requests if you or anyone else is interested in helping to improve our developer tooling for the Splunk developer community. We are absolutely doing the best we can and we thank you for your patience.
> 
> I've re-opened the issue for tracking purposes as @email2vimalraj suggested.

I took a shot at rewriting it on typescript and in the process decided to use async/await and separate them into modules/packages. Started with ModularInputs as that what i was using the sdk for. It needs some cleanup and testing but you can use it/adapt it if you want to.

[https://github.com/jose-pr/splunkts](url)

**Comment by ashah-splunk** [comment]
Promise support has been added in Javascript SDK v2.0.0
